### ISSUE TITLE
VCC connection is missing from the guide

### ISSUE THREAD

**Issue by CGenie** [drone-os/drone-book#1]
https://book.drone-os.com/bmp-from-bluepill.html
It seems you're missing 1 cable connection: 5V to VCC on the Blue Pill. Without this I got `Can't init. Ensure that BOOT0 is enabled and reset device` which is a bit misleading.
Here I found the proper connection
https://medium.com/@paramaggarwal/programming-an-stm32f103-board-using-usb-port-blue-pill-953cec0dbc86
and with that the Blue Pill bootloading worked.

**Comment by alfredch** [comment]
Quoting an answer from https://electronics.stackexchange.com/questions/351989/stm32f103c8t6-5v-pin-description
"Yes, you can connect 5 V there, but you can also use the USB socket to power the processor. The pin labeled 5V and the USB power pin are shorted together, so you should only drive one of them."
So yes, the picture may be misleading.

**Comment by valff** [comment]
Added a warning in https://github.com/drone-os/drone-book/commit/95ac79724c741fc652464f099085fb24fe74a609
