### ISSUE TITLE
Adding comparison with Tock-OS in src/introduction.md ?

### ISSUE THREAD

**Issue by JOE1994** [drone-os/drone-book#4]
Hello 😃 ,

Since `Tock-OS` is another major project in-progress to build an embedded OS in Rust,
I thought adding a section in `src/introduction.md` highlighting the key differences between `Drone-OS` and `Tock-OS` could be meaningful and helpful to newcomers.

**Comment by valff** [comment]
Hello,

There was a few comparisons to TockOS and RTFM in [users.rust-lang.org thread](https://users.rust-lang.org/t/announcing-drone-0-10/32922). I don't feel quite competent with TockOS, except that I know it fits a very different niche.
